import AuthInitializer from "@/components/AuthInitializaer";
import AuthLoadingGate from "@/components/AuthLoadingGate";
import GuestGuard from "@/components/guards/GuestGuard";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        {/* <AuthInitializer /> */}
        {/* <AuthLoadingGate> */}
          <GuestGuard>
          {children}
          </GuestGuard>
        {/* </AuthLoadingGate> */}
    </>

  )
}
