// src/config/livekit.ts
export const LIVEKIT_URL = process.env.NEXT_PUBLIC_LIVEKIT_URL!;
export const LIVEKIT_TOKEN_API = process.env.NEXT_PUBLIC_LIVEKIT_PUBLIC_API!;
export const NEXT_PUBLIC_AUTH_SERVER_URL = process.env.NEXT_PUBLIC_AUTH_SERVER_URL!;
export const TEMP_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQWxpY2VcbiIsInZpZGVvIjp7InJvb21Kb2luIjp0cnVlLCJyb29tIjoibXktcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZX0sImlzcyI6ImFwaV9rZXkiLCJleHAiOjE3NDU5ODcwNTEsIm5iZiI6MCwic3ViIjoidXNlcjEyMyJ9.PC8bgJ6LSeSNMQYUmwguVN1OYYkSbh39vJHmB6uJbTg"
export const TEMP_USER_ID = "user123"