// src/config/livekit.ts
export const LIVEKIT_URL = process.env.NEXT_PUBLIC_LIVEKIT_URL!;
export const LIVEKIT_TOKEN_API = process.env.NEXT_PUBLIC_LIVEKIT_PUBLIC_API!;
export const TEMP_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQWxpY2VcbiIsInZpZGVvIjp7InJvb21Kb2luIjp0cnVlLCJyb29tIjoibXktcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZX0sImlzcyI6ImFwaV9rZXkiLCJleHAiOjE3NDU3ODM4NDgsIm5iZiI6MCwic3ViIjoidXNlcjEyMyJ9.BdjW9aNOy7iYnM0__UuWbFvawwSA1zNUhLbOY7unW5E"
export const TEMP_USER_ID = "user123"